[package]
name = "touch"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.19", features = ["derive"] }
colored = "2.1.0"
env_logger = "0.11.5"
filetime = "0.2.25"
log = "0.4.22"
